helpdesk/helpdesk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^ticket/', include('tickets.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('userportal.urls')),
    url('', include('social_django.urls', namespace='social'))
]


if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpdesk/tickets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='tickets_index'),
    url(r'^(?P<ticket_id>[0-9]+)/$', views.details, name='detail'),
    url(r'^open/$', views.open_new, name='open_new'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/location/(?P<pk>[0-9]+)/$', views.LocationDetailView.as_view(), name='location'),
    url(r'^settings/location/add/$', views.add_location, name='add_location'),
    url(r'^settings/category/(?P<pk>[0-9]+)/$', views.CategoryDetailView.as_view(), name='category'),
    url(r'^settings/category/add/$', views.add_category, name='add_category'),
]

helpdesk/tickets/models.py
#!/usr/bin/env python
"""Provides models for tickets app.

"""

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

import django.utils.timezone

__author__ = "Winston Cadwell"
__copyright__ = "Copyright 2017, Winston Cadwell"
__licence__ = "BSD 2-Clause Licence"
__version__ = "1.0"
__email__ = "wcadwell@gmail.com"


class Location(models.Model):
    """Provides a model to store locations in.

    This model is used in Ticket to provide the user a list of
    location to select from.

    *name*
        Name of the location
    *description*
        A description of the location
    *longitude*
        Longitude of the location
    *latitude*
        Latitude of the location
    """
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    longitude = models.DecimalField(max_digits=8, decimal_places=3, null=True, blank=True)
    latitude = models.DecimalField(max_digits=8, decimal_places=3, null=True, blank=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    """Provides a model to store categories in.

    This model is used in Ticket to provide the user a list or
    categories to select from.

    *name*
        Name of the category
    *description*
        Description of the category
    """
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Ticket(models.Model):
    """Provides a model to store tickets.

    This model is used to store tickets that the user submits.

    :const:`STATUS_CHOICES`
        Tuple of Tuples containing possible choices for *status*

    *user*
        Linked to User model built into Django. Used to
        link Ticket to a specific user.
    *name*
        Used to store users name in-case it is
        different than the logged in user's.
    *description*
        A description of the problem, provided by the user.
    *status*
        Status of the ticket. This field is multiple choice, choices
        are provided by :const:`STATUS_CHOICES`.
    *priority*
        Priority value for the ticket. Can range between 1 and 5.
    *submissionDate*
        Date that the ticket was submitted.
    *location*
        :class:`Location` for the ticket.
    *category*
        :class:`Category` for the ticket.
    *ipAddress*
        Stores an IP Address associated with the ticket.
    """

    class Meta:
        permissions = (("can_view_all", "View all tickets"), ("can_open", "Open a new ticket"),
                       ("can_edit_tickets", "Has full control of tickets"))

    COMPLETE = 'C'
    WAITING = "W"
    IN_PROGRESS = "I"

    STATUS_CHOICES = (
        (COMPLETE, "Complete"),
        (IN_PROGRESS, "In Progress"),
        (WAITING, "Waiting")
    )

    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=1,
                              choices=STATUS_CHOICES,
                              default="W")
    priority = models.IntegerField(default=1, validators=[
        MinValueValidator(5),
        MaxValueValidator(1)
    ])
    submissionDate = models.DateTimeField('date submitted', default=django.utils.timezone.now)
    location = models.ForeignKey(Location, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    ipAddress = models.GenericIPAddressField(null=True, blank=True)

    def __str__(self):
        return str(self.user.username + " - " + str(self.submissionDate.date()))


class Question(models.Model):
    """This model is currently unused.

    In a future release this model will be used to store
    optional question for the user.
    """
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    questionTitle = models.CharField(max_length=100)
    questionText = models.TextField()
    questionHelpText = models.TextField()
    questionType = models.CharField(max_length=15)


class File(models.Model):
    """Model to index files uploaded by the user.

    This model stores a file and some data associated with it.

    *ticket*
        :class"`Ticket` that file is linked to.
    *description*
        Description of the file.
    *file*
        Stores uploaded file.
    *timestamp*
        Stores the time of upload.
    """
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to='uploads/', null=True, blank=True)
    timestamp = models.DateTimeField(default=django.utils.timezone.now)

    def __str__(self):
        return self.file.name.split("/")[-1]

helpdesk/tickets/forms.py
#!/usr/bin/env python
"""Provides views for tickets app.
"""

from django.forms import ModelForm, TextInput

from .models import Ticket, File, Location, Category

__author__ = "Winston Cadwell"
__copyright__ = "Copyright 2017, Winston Cadwell"
__licence__ = "BSD 2-Clause Licence"
__version__ = "1.0"
__email__ = "wcadwell@gmail.com"


class OpenForm(ModelForm):

    def __init__(self, user, *args, **kwargs):
        super(OpenForm, self).__init__(*args, **kwargs)
        self.user = user
        self.fields['name'].widget = TextInput(attrs={'value': self.user.first_name})

    class Meta:
        model = Ticket
        fields = ["name", "description", "category", "location", "ipAddress"]

        labels = {
            'ipAddress': "IP Address"
        }


class FileUploadForm(ModelForm):

    class Meta:
        model = File
        fields = ["file", "description"]

        help_texts = {
            'description': "Give a brief description of what the file is"
        }


class AddLocationForm(ModelForm):

    class Meta:
        model = Location
        fields = ["name", "description", "longitude", "latitude"]


class AddCategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ["name", "description"]

helpdesk/userportal/views.py
#!/usr/bin/env python
"""Provides views for userportal app.
"""

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin

from  .models import User

from django.contrib.auth.models import Group

from .forms import EmailPreferencesForm, UserPreferencesForm

__author__ = "Winston Cadwell"
__copyright__ = "Copyright 2017, Winston Cadwell"
__licence__ = "BSD 2-Clause Licence"
__version__ = "1.0"
__email__ = "wcadwell@gmail.com"


def is_admin(user):
    return user.groups.filter(name='Admin').exists()


# Create your views here.
def index(request):
    """Provide a home page for the user.

        GET:
            This method does not process any POST requests.

        POST:
            This method does not process any POST requests.
        """
    template = loader.get_template('userportal/index.html')
    return HttpResponse(template.render({'content': "hello"}, request))


@login_required()
def preferences(request):
    if request.method == 'POST':
        account_form = UserPreferencesForm(request.POST, instance=request.user, prefix="account")
        form = EmailPreferencesForm(request.POST, instance=request.user.emailpreferences, prefix="email")

        if form.is_valid():
            form.save()

        if account_form.is_valid():
            account_form.save()

        return redirect('/preferences/')

    else:
        account_form = UserPreferencesForm(instance=request.user, prefix="account")
        form = EmailPreferencesForm(instance=request.user.emailpreferences, prefix="email")

    template = loader.get_template('userportal/preferences.html')

    return HttpResponse(template.render({'account_form': account_form, 'form': form}, request))


class UserManagement(PermissionRequiredMixin, ListView):
    permission_required = 'auth.user.can_change_user'
    model = User
    template_name = 'userportal/user_management.html'

    def get_context_data(self, **kwargs):
        context = super(UserManagement, self).get_context_data(**kwargs)
        return context


@permission_required('user.can_add_user')
def add_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

    template = loader.get_template('userportal/add_user.html')

    form = UserCreationForm()

    return HttpResponse(template.render({'form': form}, request))


@permission_required('user.can_change_user')
def UserDetails(request, **kwargs):
    if request.method == "POST":

        form = UserChangeForm(request.POST, instance=User.objects.get(pk=kwargs.get('pk')), prefix="form")
        if form.is_valid():
            form.save()

        action = request.POST.get('action')
        if action == "delete":
            User.objects.filter(pk=kwargs.get('pk')).delete()
            return HttpResponse('')

        elif action == "toggle_admin":
            user = User.objects.get(pk=kwargs.get('pk'))
            group = Group.objects.get(name="Admin")
            if not user.groups.filter(name="Admin").count():
                user.groups.add(group)
            else:
                user.groups.remove(group)

            return HttpResponse('')

    else:

        form = UserChangeForm(instance=User.objects.get(pk=kwargs.get('pk')), prefix="form")

    template = loader.get_template('userportal/user_detail.html')

    return HttpResponse(template.render({'form': form}, request))

helpdesk/tickets/templates/tickets/add_category.html
{% extends "userportal/header.html" %}

{% block content %}

    <form action="{% url 'add_category' %}" method="post">

        {% csrf_token %}

        <table class="table">
            {{ form.as_table }}
        </table>

        <a class="btn btn-secondary" href="{{ previous_page }}">Cancel</a>
        <input class="btn btn-primary" type="submit" value="Save">

    </form>


{% endblock %}

helpdesk/tickets/templates/tickets/add_location.html
{% extends "userportal/header.html" %}

{% block content %}

    <form action="{% url 'add_location' %}" method="post">

        {% csrf_token %}

        <table class="table">
            {{ form.as_table }}
        </table>

        <a class="btn btn-secondary" href="{{ previous_page }}">Cancel</a>
        <input class="btn btn-primary" type="submit" value="Save">

    </form>


{% endblock %}

helpdesk/tickets/templates/tickets/category_detail.html
{% extends "userportal/header.html" %}

{% block content %}
    <div class="container-fluid align-content-center">
        <table class="table text-center">
            <tr>
                <td>Name:</td>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <td>Description:</td>
                <td>{{ object.description }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

helpdesk/tickets/templates/tickets/confirmation_email.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Ticket Submission Confirmation</title>
</head>
<body>
Hello {{ user.first_name }},
Your ticket had been successfully submitted.
You can find a summary below:

<table cellspacing="0" cellpadding="0" border="0" width="100%">
    <tr>
        <td align="center">
            Location: {{ ticket.location }}
        </td>
    </tr>
    <tr>
        <td align="center">
            Category: {{ ticket.category }}
        </td>
    </tr>
    <tr>
        <td align="center">
            Description: {{ ticket.description }}
        </td>
    </tr>
    <tr>
        <td align="center">
            IP Address: {{ ticket.ipAddress }}
        </td>
    </tr>
</table>
</body>
</html>

helpdesk/tickets/templates/tickets/details.html
{% extends "userportal/header.html" %}
{% block content %}

    {% csrf_token %}

    <script type="text/javascript">
        $(function () {
            // language=JQuery-CSS
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>

    <div class="card-columns">
        <div class="card">
            <div class="card-header">Details</div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>Name: </b> {{ ticket.user }}</li>
                    <li class="list-group-item"><b>E-mail: </b> {{ ticket.user.email }}</li>
                    <li class="list-group-item"><b>Location: </b> {{ ticket.location }}</li>
                    <li class="list-group-item"><b>Category: </b> {{ ticket.category }}</li>
                    <li class="list-group-item"><b>IP Address: </b> {{ ticket.ipAddress }} </li>
                </ul>
            </div>
        </div>


        <div class="card">
            <div class="card-header">Description</div>
            <div class="card-body">
                {{ ticket.description }}
            </div>
        </div>

        <div class="card">
            <div class="card-header">Media</div>
            {% if media %}
                <div class="card-body">
                    <ul class="list-unstyled">
                        {% for file in media %}
                            <li>
                                <a title="{{ file.description }}" href="/media/uploads/{{ file }}">{{ file }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <div class="card-body">
                    No Media To Show
                </div>
            {% endif %}
        </div>


        <div class="card text-white">
            <div class="card-header bg-dark">Actions</div>
            <div class="card-body">
                <div class="container">
                    <div class="form-group">
                        {% include 'tickets/status_dropdown.html' %}

                        {% include 'tickets/priority_dropdown.html' %}
                    </div>
                    <div class="form-group">
                        <button class="btn btn-outline-danger" id="delete">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(document).ready(function () {
            $("#delete").click(function () {
                if (confirm("Are you sure you want to delete this ticket?")) {
                    $.post("/ticket/{{ ticket.id }}/", {
                            csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
                            ticket_id: {{ ticket.id}},
                            action: "delete"
                        },
                        function () {
                            window.location.replace('/ticket/')
                        });
                }
            });

        });
    </script>

{% endblock %}

helpdesk/tickets/templates/tickets/file_modal.html
<div class="modal" id="fileModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                Add a file
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <table class="table">
                            {{ file_form.as_table }}
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

helpdesk/tickets/templates/tickets/index.html
{% extends "userportal/header.html" %}

{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tickets/css/grid.css' %}" type="text/css"/>

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="btn-group form-group col-1">
                <button id="masterDelete" class="btn btn-danger" disabled>Delete</button>
            </div>
            <div class="dropdown col-md-1 offset-md-10">
                <a class="dropdown-toggle btn btn-secondary" id="dropdown-filter"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="true">Filter
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdown-filter">
                        <a class="dropdown-item" href="?show_completed=true">Show Completed</a>
                </div>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover">
                <thead class="thead-light">
                <th><input type="checkbox" class="checkbox" id="masterCheckbox"></th>
                <th><a href="?order_by=-name">Name</a></th>
                <th>Description</th>
                <th><a href="?order_by=-submissionDate">Date Submitted</a></th>
                <th><a href="?order_by=-priority">Priority</a></th>
                <th><a href="?order_by=-status">Status</a></th>
                </thead>
                {% if ticket_list %}
                    {% for ticket in ticket_list %}
                        <tbody>
                        <tr>
                            <td><input type="checkbox" class="checkbox ticketCheckbox"
                                       data-tid="{{ ticket.id }}"></td>
                            <td><a href="/ticket/{{ ticket.id }}/">{{ ticket.name }}</a></td>
                            <td><p>{{ ticket.description }}</p></td>
                            <td>{{ ticket.submissionDate }}</td>
                            <td>{{ ticket.priority }}</td>
                            <td>{% include 'tickets/status_dropdown.html' %}</td>
                        </tr>
                        </tbody>
                    {% endfor %}
                {% else %}
                    <tr>
                        <div class="alert alert-warning" role="alert">
                            Your query returned no tickets. Please try a different query.
                        </div>
                    </tr>

                {% endif %}
            </table>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {

            $("#masterCheckbox:checkbox").change(function () {
                if ($(this).is(":checked")) {
                    $(".ticketCheckbox").prop("checked", true)
                }
                else {
                    $(".ticketCheckbox").prop("checked", false)
                }
                $("#masterDelete").prop("disabled", checkBoxes.filter(':checked').length < 1)
            });

            let checkBoxes = $('.ticketCheckbox');
            checkBoxes.change(function () {
                $("#masterDelete").prop("disabled", checkBoxes.filter(':checked').length < 1)
            });

            $("#masterDelete").click(function () {
                if (confirm("Are you sure you want to delete the selected items?")) {
                    let checked = checkBoxes.filter(':checked');
                    for (let i = 0; i < checked.length; i++) {
                        $(checked[i]).prop("checked", false);
                        $("#masterDelete").prop("disabled", checkBoxes.filter(':checked').length < 1)
                        $.post(("/ticket/" + $(checked[i]).data('tid') + "/"), {
                                csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
                                ticket_id: $(checked[i]).data('tid'),
                                action: "delete"
                            },
                            function () {
                                window.location.reload(false)
                            }
                        );
                    }
                }
            });
        });
    </script>

{% endblock %}

helpdesk/tickets/templates/tickets/location_detail.html
{% extends "userportal/header.html" %}

{% block content %}
    <div class="container-fluid align-content-center">
        <table class="table text-center  ">
            <tr>
                <td>Name:</td>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <td>Description:</td>
                <td>{{ object.description }}</td>
            </tr>
            <tr>
                <td>Longitude:</td>
                <td>{{ object.logitude }}</td>
            </tr>
            <tr>
                <td>Latitude:</td>
                <td>{{ object.latitiude }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

helpdesk/tickets/templates/tickets/open.html
{% extends "userportal/header.html" %}

{% load staticfiles %}
<link rel="stylesheet" href="{% static 'tickets/css/grid.css' %}" type="text/css"/>

{% block content %}

    <h4>Please verify this information is correct:</h4>

    <form action="/ticket/open/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">

            {{ form.as_table }}

            <tr>
                <th>File Upload:</th>
                <td>
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#fileModal">
                        Attach File
                    </button>

                </td>
            </tr>

        </table>
        <input class="btn btn-primary" type="submit" value="Submit"/>


        {% include 'tickets/file_modal.html' %}

    </form>



{% endblock %}
--/>

helpdesk/tickets/templates/tickets/priority_dropdown.html
<a class="dropdown">
    <button class="btn dropdown-toggle btn-primary"
            id="ticket{{ ticket.id }}"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">{{ ticket.priority }}</button>
    <div class="dropdown-menu" aria-labelledby="ticket{{ ticket.id }}">
        {% csrf_token %}
        <button class="dropdown-item priorityToggle" data-priority="1"
                data-ticket="{{ ticket.id }}">1
        </button>
        <button class="dropdown-item priorityToggle" data-priority="2"
                data-ticket="{{ ticket.id }}">2
        </button>
        <button class="dropdown-item priorityToggle" data-priority="3"
                data-ticket="{{ ticket.id }}">3
        </button>
        <button class="dropdown-item priorityToggle" data-priority="4"
                data-ticket="{{ ticket.id }}">4
        </button>
        <button class="dropdown-item priorityToggle" data-priority="5"
                data-ticket="{{ ticket.id }}">5
        </button>

    </div>
</a>

<script>
    $(document).ready(function () {
        $('.priorityToggle').click(function () {
            $.post(("/ticket/" + $(this).data('ticket') + "/"), {
                    csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
                    ticket_id: $(this).data('ticket'),
                    action: "priority",
                    value: $(this).data('priority')
                },
                function () {
                    window.location.reload(false)
                });
        });
    });
</script>

helpdesk/tickets/templates/tickets/status_dropdown.html
<a class="dropdown">
    <button class="btn dropdown-toggle
                                {% if ticket.status == "W" %} btn-danger
                                {% elif ticket.status == "I" %} btn-warning
                                {% elif ticket.status == "C" %} btn-success
                                {% endif %}"
            id="ticket{{ ticket.id }}"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">{{ ticket.get_status_display }}</button>
    <div class="dropdown-menu" aria-labelledby="ticket{{ ticket.id }}">
        {% csrf_token %}
        <button id="W{{ ticket.id }}" class="dropdown-item statusToggle" data-status="W"
                data-ticket="{{ ticket.id }}">Waiting
        </button>
        <button id="I{{ ticket.id }}" class="dropdown-item statusToggle" data-status="I"
                data-ticket="{{ ticket.id }}">In Progress
        </button>
        <button if="C{{ ticket.id }}" class="dropdown-item statusToggle" data-status="C"
                data-ticket="{{ ticket.id }}">Complete
        </button>
    </div>
</a>

<script>
    $(document).ready(function () {
        $('.statusToggle').click(function () {
            $.post(("/ticket/" + $(this).data('ticket') + "/"), {
                    csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
                    ticket_id: $(this).data('ticket'),
                    action: "status",
                    value: $(this).data('status')
                },
                function (data, status) {
                    window.location.reload(false)
                });
        });
    });
</script>